/* Products Data — 26 items across 5 categories */

export const storeProducts = [
  /* ===== ELECTRONICS ===== */
  {
    id: 1,
    title: 'Google Pixel 8 Pro',
    img: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=480&h=480&fit=crop&auto=format&q=80',
    price: 25499,
    company: 'Google',
    category: 'electronics',
    info: 'Experience pure Android with the Google Pixel 8 Pro. Features an exceptional AI-powered camera system, 7 years of OS updates, and the Tensor G3 chip for blazing performance.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: 'Samsung Galaxy S24 Ultra',
    img: 'https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?w=480&h=480&fit=crop&auto=format&q=80',
    price: 33999,
    company: 'Samsung',
    category: 'electronics',
    info: 'The Samsung Galaxy S24 Ultra with built-in S Pen, 200MP camera, titanium frame, and the most powerful Galaxy AI features to date.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: 'iPhone 15 Pro',
    img: 'https://images.unsplash.com/photo-1678652197831-2d180705cd2c?w=480&h=480&fit=crop&auto=format&q=80',
    price: 42499,
    company: 'Apple',
    category: 'electronics',
    info: 'iPhone 15 Pro with A17 Pro chip, titanium design, and the most advanced camera system ever on an iPhone including 5x optical zoom.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: 'iPad Pro M2',
    img: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=480&h=480&fit=crop&auto=format&q=80',
    price: 50999,
    company: 'Apple',
    category: 'electronics',
    info: 'The iPad Pro with M2 chip and Liquid Retina XDR display — a stunning canvas for creativity. Supports Apple Pencil and Magic Keyboard.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: 'OnePlus 12',
    img: 'https://images.unsplash.com/photo-1609692814858-f7cd2f0afa4f?w=480&h=480&fit=crop&auto=format&q=80',
    price: 21199,
    company: 'OnePlus',
    category: 'electronics',
    info: 'Blazing fast Snapdragon 8 Gen 3, 100W SUPERVOOC charging, a silky-smooth 120Hz AMOLED display, and the Hasselblad-tuned triple camera.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: 'Apple Watch Series 9',
    img: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=480&h=480&fit=crop&auto=format&q=80',
    price: 15199,
    company: 'Apple',
    category: 'electronics',
    info: 'Apple Watch Series 9 — the most capable Apple Watch ever. Advanced health monitoring, crash detection, double tap gesture, and the brightest display.',
    inCart: false,
    count: 0,
    total: 0,
  },

  /* ===== GROCERIES ===== */
  {
    id: 7,
    title: 'Organic Fresh Apples',
    img: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=480&h=480&fit=crop&auto=format&q=80',
    price: 199,
    company: 'FreshFarm',
    category: 'groceries',
    info: 'Hand-picked organic Fuji apples, crisp and naturally sweet. Rich in antioxidants and dietary fiber. Sustainably grown, no pesticides. Pack of 6.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: 'Full Cream Milk 1L',
    img: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=480&h=480&fit=crop&auto=format&q=80',
    price: 75,
    company: 'DairyBest',
    category: 'groceries',
    info: 'Farm-fresh full cream milk, pasteurized and homogenized. Rich in calcium, vitamins A & D, and natural proteins. 1-litre pack. Best before 7 days.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: 'Artisan Sourdough Bread',
    img: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=480&h=480&fit=crop&auto=format&q=80',
    price: 149,
    company: 'BreadCraft',
    category: 'groceries',
    info: 'Handcrafted sourdough loaf with a perfectly crisp crust and chewy open crumb. Made with a 48-hour fermentation process, no preservatives added.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: 'Premium Ground Coffee',
    img: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=480&h=480&fit=crop&auto=format&q=80',
    price: 499,
    company: 'CoffeeBean Co.',
    category: 'groceries',
    info: 'Single-origin Ethiopian arabica, medium-dark roast. Notes of dark chocolate, blueberry, and caramel. Freshly ground to order. 250g bag.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    title: 'Wild Atlantic Salmon',
    img: 'https://images.unsplash.com/photo-1499028344343-cd173ffc68a9?w=480&h=480&fit=crop&auto=format&q=80',
    price: 899,
    company: 'OceanFresh',
    category: 'groceries',
    info: 'Premium wild-caught Atlantic salmon fillet, rich in Omega-3 fatty acids. Sustainably sourced with MSC certification. Vacuum-sealed for freshness. 500g.',
    inCart: false,
    count: 0,
    total: 0,
  },

  /* ===== FURNITURE ===== */
  {
    id: 12,
    title: 'Modern Comfort Sofa',
    img: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=480&h=480&fit=crop&auto=format&q=80',
    price: 49999,
    company: 'HomeCraft',
    category: 'furniture',
    info: 'Luxurious 3-seater sofa with high-density foam cushions and premium linen upholstery. Solid beech wood frame. Available in 5 colors. Assembly included.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 13,
    title: 'Oak Dining Table Set',
    img: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=480&h=480&fit=crop&auto=format&q=80',
    price: 34999,
    company: 'WoodWorks',
    category: 'furniture',
    info: 'Solid oak dining table with 4 matching chairs. Seats 6 comfortably. Water-resistant lacquer finish. Dimensions: 180×90cm. Easy self-assembly.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 14,
    title: 'Ergonomic Office Chair',
    img: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=480&h=480&fit=crop&auto=format&q=80',
    price: 18999,
    company: 'ErgoPlus',
    category: 'furniture',
    info: 'Premium ergonomic task chair with lumbar support, adjustable armrests, headrest, and breathable mesh back. Supports up to 150kg. 5-year warranty.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 15,
    title: 'Floating Wall Bookshelf',
    img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=480&h=480&fit=crop&auto=format&q=80',
    price: 5999,
    company: 'ShelfKing',
    category: 'furniture',
    info: 'Modern floating wall-mounted bookshelf in solid walnut. Set of 3 shelves. Holds up to 50kg each. Easy installation with concealed hidden-bracket hardware.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 16,
    title: 'King Size Bed Frame',
    img: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=480&h=480&fit=crop&auto=format&q=80',
    price: 42999,
    company: 'SleepWell',
    category: 'furniture',
    info: 'Solid pine king-size bed frame with elegant padded headboard. Strong slat system supports up to 250kg. Includes center support beam. 180×200cm.',
    inCart: false,
    count: 0,
    total: 0,
  },

  /* ===== FASHION ===== */
  {
    id: 17,
    title: 'Classic Denim Jacket',
    img: 'https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=480&h=480&fit=crop&auto=format&q=80',
    price: 2999,
    company: 'DenimCo',
    category: 'fashion',
    info: 'Timeless slim-fit denim jacket crafted from 100% sanforized cotton. Reinforced stitching at stress points. Pre-washed for a broken-in feel. Sizes XS–XXL.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 18,
    title: 'Nike Air Max Sneakers',
    img: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=480&h=480&fit=crop&auto=format&q=80',
    price: 7499,
    company: 'Nike',
    category: 'fashion',
    info: 'Iconic Nike Air Max sneakers with visible cushioning for superior all-day comfort. Breathable engineered mesh upper. Rubber outsole for grip. Sizes 6–13.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 19,
    title: 'Floral Midi Dress',
    img: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=480&h=480&fit=crop&auto=format&q=80',
    price: 1799,
    company: 'StyleHouse',
    category: 'fashion',
    info: 'Elegant wrap-effect floral midi dress in lightweight chiffon. Adjustable tie waist, flutter sleeves. Perfect for both casual and semi-formal occasions.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 20,
    title: 'Luxury Chronograph Watch',
    img: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=480&h=480&fit=crop&auto=format&q=80',
    price: 12999,
    company: 'TimeCraft',
    category: 'fashion',
    info: 'Swiss-movement chronograph with sapphire crystal glass, 316L stainless steel case, and genuine Italian leather strap. Water resistant to 50m.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 21,
    title: 'Leather Crossbody Bag',
    img: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=480&h=480&fit=crop&auto=format&q=80',
    price: 3499,
    company: 'LeatherLux',
    category: 'fashion',
    info: 'Genuine full-grain leather crossbody bag with multiple zip compartments, RFID-blocking inner pocket, and adjustable shoulder strap. Handcrafted in Italy.',
    inCart: false,
    count: 0,
    total: 0,
  },

  /* ===== SPORTS ===== */
  {
    id: 22,
    title: 'Premium Yoga Mat',
    img: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=480&h=480&fit=crop&auto=format&q=80',
    price: 1299,
    company: 'ZenFit',
    category: 'sports',
    info: '6mm thick non-slip yoga mat with body-alignment lines printed on both sides. Eco-friendly TPE material, latex-free. Includes carry strap. 183×61cm.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 23,
    title: 'Adjustable Dumbbells Set',
    img: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=480&h=480&fit=crop&auto=format&q=80',
    price: 8999,
    company: 'IronGrip',
    category: 'sports',
    info: 'All-in-one adjustable dumbbell pair ranging from 2.5kg to 30kg. Quick-select dial mechanism. Replaces 8 pairs of dumbbells. Compact tray storage.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 24,
    title: 'Official NBA Basketball',
    img: 'https://images.unsplash.com/photo-1519861531473-9200262188bf?w=480&h=480&fit=crop&auto=format&q=80',
    price: 1499,
    company: 'SportsPro',
    category: 'sports',
    info: 'Official size & weight NBA game basketball. Deep channel design for superior grip and control. Suitable for indoor and outdoor courts. Size 7.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 25,
    title: 'Carbon Fibre Badminton Racket',
    img: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=480&h=480&fit=crop&auto=format&q=80',
    price: 2499,
    company: 'SpeedSwing',
    category: 'sports',
    info: 'Professional-grade carbon fibre badminton racket at 85g ultra-lightweight. Even balance for power and control. Pre-strung at 24lbs tension. Includes bag.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 26,
    title: 'Pro Running Shoes',
    img: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=480&h=480&fit=crop&auto=format&q=80',
    price: 4999,
    company: 'SpeedRun',
    category: 'sports',
    info: 'Advanced cushioning with responsive ReactX foam midsole and breathable knit upper. Engineered for marathon training. Reflective details for night runs.',
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = storeProducts[0];
